---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd-adm
  namespace: adm
spec:
  releaseName: linkerd-adm
  chart:
    repository: https://helm.linkerd.io/stable
    version: 2.6.1
    name: linkerd2
  values:
    Identity:
      TrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBwDCCAWagAwIBAgIQI+Q3NHTgnAFO/8pkU2DV5zAKBggqhkjOPQQDAjApMScw
        JQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAwMTIy
        MTUxODA2WhcNMzAwMTE5MTUxODA2WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5r
        ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQzsd5V
        Pn/cHvtRgQpf1DQOWfc/GBkj+yDmbvzrO8ngg4QPjGgTSkLsOz61i5ZUuLY4u4mp
        Jph5BbBKkpSD1YmPo3AwbjAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB
        /wIBATAdBgNVHQ4EFgQU3vsZcFOK85A8oJwq1q01xDAL8D8wKQYDVR0RBCIwIIIe
        aWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0gAMEUC
        IAZc7OaLlznNzm/FVu3cfZPzUUwTFRJfBTaAKf0ibD74AiEA3z1Pw+Pqz0xKT0+y
        ame0mSNUPLVnGGu+qqnthP6rIu0=
        -----END CERTIFICATE-----
      Issuer:
        TLS:
          CrtPEM: |
            -----BEGIN CERTIFICATE-----
            MIIBvzCCAWagAwIBAgIQIPpTlBlHG/N1AA/Dyv6z9zAKBggqhkjOPQQDAjApMScw
            JQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAwMTIy
            MTUxODM4WhcNMjEwMTIxMTUxODM4WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5r
            ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQfEkGP
            S4dd82vLpeTL75+anz5PTaZiwrKGmG00uA81ZPywy/J/RzHQBgpcGMS2ej+Qrwg/
            UuwTj0DAFJ5ikWJgo3AwbjAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB
            /wIBADAdBgNVHQ4EFgQU4fvcaygL7jAebrLqvRyoDMQFAd4wKQYDVR0RBCIwIIIe
            aWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0cAMEQC
            IDyJfixtTb96+IQc0c22YHF2DPNS0ApvGRMgc7vGkKI7AiBjPzoEw+FOgYDQvFiU
            RDpeEnpKJ+DmW+YssU3qukvxQg==
            -----END CERTIFICATE-----
          KeyPEM: |
              -----BEGIN EC PRIVATE KEY-----
              MHcCAQEEIN0Qu1F93xQ4qUXsj8loZy+CYgn4h2xt8vJ5oZha0gW5oAoGCCqGSM49
              AwEHoUQDQgAEHxJBj0uHXfNry6Xky++fmp8+T02mYsKyhphtNLgPNWT8sMvyf0cx
              0AYKXBjEtno/kK8IP1LsE49AwBSeYpFiYA==
              -----END EC PRIVATE KEY-----
        CrtExpiry: 2021-01-21T10:36:38Z
