apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgA0OLSvefvoJBudGaRJYEci1CLGkzYWSp3u76M2RUdsbGjKuH0p7GEvFC6pq5Q/FBNQe0/rYeLx2fycnwSoV2wJZDEC3QTKrPOwSoC1R+g0a0A1yYmDAp8oxXJvwBD1Kb5rU1qJ+aYnQsZLxP2OqQLAd6dMYXz1P208G4uMaHd75aYXJ7ubdAMXqaD4TAHEdviRIopwJLMf+cganVPmyq276lGGQk4tUwjT8OMrYRQllxuqzy5GiPievEq2K00lE1EiAypPitRM4eaudXbE4URngwYqVoWLM+6lZhZbdBq0F2R3KfPv0xZ98YTUS2NDnVNLkwwl9sV6ST1cUvsgBH82oRGY7mJd8UGXcbREDO7tnNnvjbBaOnbiKV6eERMqYDv6JAQB4r8xO9+G8Ms/j9rkIpZik5qu/3QDr3YkhCKzjRQwm12+/uT1K12EiO8gx56F4P5qHS/8kKLEZJUjphybou2SdAQevWbt99wCfdbIofmOh8jmV2wfbLX96OGD0gTw8Ztu8dH4HOWwYCyQT6RtTURg7AmzhtENpy81BbNDvxT92kxGqSxg28PkxxVYkbmEJcHE3+V3py0o2QN5RnANXpTXpE9u8REyKcHiYJhwKTWtihxZLC8P/fShW02jrO/oxD8cqvv5QGH+wdguVzmqWZbzJdyzYtwFNZN3YW1gRkIZarmBQUJe97aUUXy6y/o/mdk0fg==
    user: AgA21W6m9pN/nlkIx3SBtCvyN8FOCLtlHz5deih2yxmk7TMXYaZcdNeSv4VangG4iMaV5AACarXCLcnQ6suAhL7BfldCqgckxQWqgsca3uFiJRmOSaUZ+V6terkTyCTiMdaEX3LGorva6wp63TQiy3Vzq46VJxuwJTUPJwub4rONv+ZEWOc+GeJEBTyQBeMExCxEYsi2/UG/zR0HKHTqXOhBn8aiIa1Zz52nfuSUTt9Kgq58+fpFLK27NRXAcB8yK07yTG+xb6XKArKV/mTBQbKxmxPgbFV2lbMfPBnAu7wN7OHpk/IrkcRcaB8797rkPuO3T950H69ZAc8GWJmqjd5caritQ0RqEuy8Hv74cV2fYnLm5bwbRAfFL5UmYjg0Z9ttXSpBIIywmAPHYD+9SEMBSmamhYqNLjY3zevfFI9H0ZyJUYrqONhQMYWCSohajK80FEJ3hIkrjC/Ou6SUUdR9gCRbJyDTyEYgGIrg8+P53QdeuGlGF/gmrbmxQ9WvE/+fP7aeT1gMJtN4btdYEdOphobZjLcf3GKbcjBYtWjn9hyWjSjLSxJBn2ZB9A3cII6mzbhYG5vh6BXZTbub35rzXel7jdUKzfcnWIwoXkxhnHV9XSApcKs95/yODxKq0Rm9rJXJzCuhwbFau+FDf4L59w8QBtkYRr6BD7+iHnb/kK6S/92VmYjGhj4WuY2lZ/CNhZ9XQw==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev
status: {}

