---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:dev-*
    linkerd.io/inject: enabled
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:sebastianortizs4n/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.1.5
    replicaCount: 1
    hpa:
      enabled: false
    ingress:
      enabled: true
    linkerd:
      profile:
        enabled: true

